### ISSUE TITLE
Item Roller Duplicates

### ISSUE THREAD

**Issue by MICAHANIMATRIX** [JustDerb/RoR2-VsTwitch#1]
This is probably an issue that is already well known, but in case it isn't I thought I would make a point of posting this anyways. It's not uncommon for there to be two identical options, and during stream we actually got 3 identical options twice.
![20201210171912_1](https://user-images.githubusercontent.com/12789478/101878541-9a736200-3b44-11eb-9192-e59506c96f28.jpg)

**Comment by MICAHANIMATRIX** [comment]
I'm also not sure if this is intended or not, but when opening scavenger bags, chat picks all 10 items that drop, which slows down the stream significantly

**Comment by JustDerb** [comment]
So the item rolling is what the vanilla RoR2 code is doing - you can actually get "lucky" and see a multi-shop with 3 of the same item! I'll look into possibly adding a new config value to force re-rolls if this occurs (I'll be defaulting it off to keep the same rolling behavior as vanilla).

> I'm also not sure if this is intended or not, but when opening scavenger bags, chat picks all 10 items that drop, which slows down the stream significantly

This was intended and can make things a bit slow (since you've effectively opened 10 "chests"). I might look into adding another option where maybe chat picks one of three choices and then you get 10x of them, or having it disabled outright.
