### ISSUE TITLE
Question: Does this mod synchronize with the in-game chat box with Twitch Chat?

### ISSUE THREAD

**Issue by KaitoXion** [JustDerb/RoR2-VsTwitch#57]
Would like to ask a question;
> Does this mod synchronize with the in-game chat box with Twitch Chat?

Similar to this mod, where it will synchronize the in-game chat box with Twitch Chat.
https://thunderstore.io/package/OrangeNote/TwitchIntegration/

As I believe it will be quite hard to check the chat on twitch during game play.

I still do not fully understands how this mod works. It appear VsTwitch do not auto-retrieve token when twitch account is logged in.
Did be interesting to find out more.

**Comment by JustDerb** [comment]
I haven't added the chat feature mainly due to the in-game chat being very small, and so for folks that have >20 active chatters the in-game chat box can become impossible to read. In most cases I know a lot of streamers use a second monitor (or their phone) to look at chat. Or, they simply run the game in windowed mode!

> I still do not fully understands how this mod works. It appear VsTwitch do not auto-retrieve token when twitch account is logged in.

The guide for the initial setup can be found in the README: https://github.com/JustDerb/RoR2-VsTwitch?tab=readme-ov-file#first-time-setup

If you have any issues, feel free to add a comment below!

**Comment by KaitoXion** [comment]
I see.
Noted. Thank you very much for your kind reply. :)
